# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9592e79561d335c9fec8c5b2de397754ca1406bf940b0f9f7eedc6f8373d50d755a9897b662ec737f9973c9bac9027fcae9b4c11db1553c54410fd2fbdf8d9a

test:
  secret_key_base: d0ffe215daffb3eb2dc7e49dd5c780e4f51092795130a0bf597ab0cc234eb4ff57384e47f5b4d0573c8e76d4184084dbd6a0223f81eaf0db1df016e01be648e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
